apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: anthropic-router
  namespace: vllm
spec:
  parentRefs:
    - name: main-gateway
      namespace: kube-system
  hostnames:
    - "anthropic.sir-alfred.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: anthropic-router
          port: 3456
